# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0004_auto_20171127_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='realisation',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='suppression',
        ),
    ]
