# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0005_auto_20171204_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='realisation',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='suppression',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='non', max_length=10, null=True),
        ),
    ]
