# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0007_demande_indication'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='heure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='indication',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
