# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0008_auto_20171204_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='ipp',
        ),
    ]
