# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patient', '0009_remove_demande_ipp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='degre_urgence',
            field=models.CharField(choices=[('H24', 'H24'), ('immédiat', 'immédiat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='injection',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('à voir', 'à voir')], max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='type_examen',
            field=models.CharField(choices=[('scanner cerebral', 'scanner cerebral'), ('scanner AP', 'scanner AP'), ('scanner TAP', 'scanner TAP'), ('angioscanner pulmonaire', 'angioscanner pulmonaire'), ('uroscanner', 'uroscanner'), ('scanner Thoracique', 'scanner thoracique')], max_length=10),
        ),
    ]
